services:
  mysql:
    image: mysql:8.4
    container_name: bookmyevent-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Api/src/Database/Schema.sql:/docker-entrypoint-initdb.d/Schema.sql:ro

  redis:
    image: redis:7-alpine
    container_name: bookmyevent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
